// <auto-generated />
using System;
using GasForecast.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GasForecast.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GasForecast.Models.ElectricalPowerStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveUnitsCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GasConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ElectricalPowerStations");
                });

            modelBuilder.Entity("GasForecast.Models.ElectricalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPowerPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitType")
                        .IsUnique();

                    b.ToTable("ElectricalUnits");
                });

            modelBuilder.Entity("GasForecast.Models.ElectricalUnitPassport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConsumptionNorm")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RatedPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandartPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ElectricalUnitPassports");
                });

            modelBuilder.Entity("GasForecast.Models.ElectricalUnit", b =>
                {
                    b.HasOne("GasForecast.Models.ElectricalPowerStation", null)
                        .WithMany()
                        .HasForeignKey("UnitType")
                        .HasPrincipalKey("UnitType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GasForecast.Models.ElectricalUnitPassport", null)
                        .WithOne()
                        .HasForeignKey("GasForecast.Models.ElectricalUnit", "UnitType")
                        .HasPrincipalKey("GasForecast.Models.ElectricalUnitPassport", "UnitType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
